# Generated by Django 5.2.5 on 2025-08-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userprofile_author_page_link_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='genre',
            field=models.CharField(blank=True, choices=[('genre1', 'Жанр 1'), ('genre2', 'Жанр 2'), ('genre3', 'Жанр 3'), ('genre4', 'Жанр 4')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groupsize',
            field=models.CharField(blank=True, choices=[('size1', '<100'), ('size2', '100-500'), ('size3', '500-1000'), ('size4', '>1000')], max_length=10, null=True),
        ),
    ]
