# Generated by Django 5.2.5 on 2025-09-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userprofile_genre_userprofile_groupsize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='groupsize',
        ),
        migrations.AddField(
            model_name='blogrequest',
            name='available_dates',
            field=models.TextField(blank=True, verbose_name='Свободные даты для блога (разделить запятой)'),
        ),
        migrations.AddField(
            model_name='blogrequest',
            name='litnet_link',
            field=models.URLField(blank=True, max_length=500, verbose_name='Страница автора на Литнет'),
        ),
        migrations.AddField(
            model_name='blogrequest',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата старта'),
        ),
        migrations.AddField(
            model_name='blogrequest',
            name='vk_link',
            field=models.URLField(blank=True, max_length=500, verbose_name='Страница автора VK'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='genres',
            field=models.CharField(blank=True, choices=[('genre1', 'Жанр 1'), ('genre2', 'Жанр 2'), ('genre3', 'Жанр 3'), ('genre4', 'Жанр 4')], max_length=50, verbose_name='Жанры автора'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_book_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Набор на последней книге'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='litnet_link',
            field=models.URLField(blank=True, max_length=500, verbose_name='Страница автора на Литнет'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscribers_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество подписчиков'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vk_link',
            field=models.URLField(blank=True, max_length=500, verbose_name='Страница автора VK'),
        ),
    ]
