# Generated by Django 5.2.5 on 2025-09-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_userprofile_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogrequest',
            name='available_dates',
        ),
        migrations.AddField(
            model_name='blogrequest',
            name='available_from',
            field=models.DateField(blank=True, null=True, verbose_name='Можно начать с'),
        ),
        migrations.AddField(
            model_name='blogrequest',
            name='available_to',
            field=models.DateField(blank=True, null=True, verbose_name='Можно закончить по'),
        ),
    ]
