# Generated by Django 5.2.5 on 2025-09-03 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_blogrequest_available_dates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogrequest',
            name='date_exchange',
        ),
    ]
