# Generated by Django 5.2.5 on 2025-09-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_blogrequest_date_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogrequest',
            name='available_from',
            field=models.DateField(default='2025-09-03', verbose_name='Можно начать с'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogrequest',
            name='available_to',
            field=models.DateField(default='2025-09-03', verbose_name='Можно закончить по'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogrequest',
            name='litnet_link',
            field=models.URLField(max_length=500, verbose_name='Страница автора на Литнет'),
        ),
        migrations.AlterField(
            model_name='blogrequest',
            name='start_date',
            field=models.DateField(default='2025-09-03', verbose_name='Дата старта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogrequest',
            name='vk_link',
            field=models.URLField(max_length=500, verbose_name='Страница автора VK'),
        ),
    ]
