# Generated by Django 5.2.5 on 2025-09-08 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_blogrequest_available_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_book_title',
        ),
    ]
