# Generated by Django 5.2.5 on 2025-09-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_userprofile_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subscribers_count',
            field=models.CharField(blank=True, default='<100', verbose_name='Количество подписчиков'),
            preserve_default=False,
        ),
    ]
