# Generated by Django 5.2.5 on 2025-09-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_userprofile_subscribers_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrequest',
            name='share_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата когда нужно сделать репост'),
        ),
    ]
