# Generated by Django 5.2.5 on 2025-09-23 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_savedrequest_share_due_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogrequest',
            name='author_page_link',
            field=models.URLField(default='https://github.com', max_length=500, verbose_name='Ссылка на книгу'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='savedrequest',
            constraint=models.UniqueConstraint(fields=('request', 'share_due_date'), name='unique_share_date_per_request'),
        ),
    ]
