# Generated by Django 5.2.5 on 2025-09-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_blogrequest_author_page_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='unavailable_dates',
            field=models.JSONField(blank=True, default=list, verbose_name='Недоступные даты'),
        ),
    ]
