# Generated by Django 5.2.5 on 2025-09-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_userprofile_unavailable_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='unavailable_dates',
        ),
        migrations.AddField(
            model_name='blogrequest',
            name='unavailable_dates',
            field=models.JSONField(blank=True, default=list, verbose_name='Недоступные даты'),
        ),
    ]
