# Generated by Django 5.2.5 on 2025-09-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_userprofile_unavailable_dates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogrequest',
            name='unavailable_dates',
            field=models.JSONField(blank=True, default=list, verbose_name='Недоступные даты (для этой заявки)'),
        ),
    ]
