# Generated by Django 5.2.5 on 2025-09-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_blogrequest_unavailable_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subscribers_count',
            field=models.CharField(blank=True, choices=[('size1', '<100'), ('size2', '100-500'), ('size3', '500-1000'), ('size4', '>1000')], verbose_name='Количество подписчиков'),
        ),
    ]
